version: "3.9"
services:
  rest-app:    
    build: ./
    restart: always
    ports: 
      - "${PORT}:${PORT}"
    depends_on:
      - rest-db
      
  rest-db:    
    build: ./database
    restart: always
    ports: 
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:      
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"      
    
 